import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Cursor,
  CursorContainer,
  CursorFollow,
  CursorProvider,
} from "@/components/animate-ui/primitives/animate/cursor";
import { ThemeProvider } from "@/components/providers/themeProvider";
import ToggleTheme from "@/components/toggleTheme";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <CursorProvider>
          <CursorContainer>
            <CursorFollow className="bg-foreground/20 backdrop-blur-sm border border-foreground/40 w-8 h-8 md:w-12 md:h-12" />
            {/* <Cursor className="bg-foreground w-3 h-3 md:w-4 md:h-4" /> */}
          </CursorContainer>
        </CursorProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToggleTheme />
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            {children}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
